### ISSUE TITLE
Independence from graph database type

### ISSUE THREAD

**Issue by RioluM** [GRISERA/grisera-framework#12]
Due to huge variety of graph databases and graph query languages it could be hard to make service which can use all of them. One solution I came up with is to prepare smth like template of graph query language, which we want to implement in service. Other one is to prepare code for every type of gql, but it seems not good solution, because of a large number of them. Maybe there could be other way to fulfill this requirement.

**Comment by mrwrob** [comment]
I would follow the YAGNI principle. 
> "Always implement things when you actually need them, never when you just foresee that you need them."

It's true that there are number of graph databases and query languages. However, our prime target is Neo4J, at least for now. Maybe one or two bases will be added in the future. I doubt there will be more. 

Keeping with another principle, KISS, I think we should implement universal endpoints in `graph_api` and then at the class level implement interaction with a specific DB - for now just Neo4J.

**Comment by RioluM** [comment]
That dispels my doubts
I close the issue
